<?php
$textos = array(
    "homebb1" => array("es" => "Grupo de 8 apartamentos categoría 3 llaves situados a pie de playa en Calan forcat Con Jardín y piscina","en" => "Group of 8 apartments category 3 keys located at the foot of the beach in Calan forcat With garden and pool", "fr" => "Groupe de 8 appartements de catégorie 3 touches situées sur la plage de Calan forcat avec jardin et piscine", "it" => "Gruppo di 8 appartamenti, di categoria 3 tasti situati sulla spiaggia di Calan Forcat con giardino e piscina", "de" => "Gruppe 8 Wohnungen der Kategorie 3 am Strand in Calan forcat gelegen Schlüssel mit Garten und Pool"),
    "homebb2" => array("es" => "Grupo de 7 apartamentos de 2 y 3 habitacines categoría 3 llaves Situado entre Calas Picas, C Blanes y Calan forcat con Jardin y Piscina","en" => "Group of 7 apartments of 2 and 3 rooms category 3 keys Located between Calas Picas, C Blanes and Calan forcat with Garden and Pool", "fr" => "Groupe 7 appartements de 2 et 3 chambres 3 clés catégorie Situé entre Calas Picas, C Blanes et Calan forcat avec jardin et piscine", "it" => "Gruppo 7 appartamenti di 2 e 3 camere da letto 3 chiavi categoria Situato tra Calas Picas, C Blanes e Calan Forcat con giardino e piscina", "de" => "Gruppe 7 Wohnungen von 2 und 3 Schlafzimmer 3 Schlüssel Kategorie liegt zwischen Calas Picas, C Blanes und Calan forcat mit Garten und Pool"),
    "apartamentos" => array("es"=>"Apartamentos", "en" => "Apartments", "fr" => "Appartements", "it" => "Appartamenti", "de" => "Wohnungen"),
    "masinfo" => array("es"=>"Mas Informacion", "en" => "More Information", "fr" => "Plus d'informations", "it" => "Più informazioni", "de" => "Mehr Informationen"),
    "infobb1" => array("es"=>"Apartamento con una habitacion para dos/tres personas con terraza individual con vistas al mar. El apartamento dispone de aire acondicionado y calefaccion, WIFI gratis, caja fuerte gratuita y piscina comunitaria con tumbonas y ducha.", "en" => "Apartment with one room for two / three people with individual terrace overlooking the sea. The apartment has air conditioning and heating, Free WIFI, free safe and communal pool with sunbeds and shower.", "fr" => "Un appartement d'une chambre pour deux / trois personnes avec terrasse privée donnant sur la mer. L'appartement dispose de la climatisation et du chauffage, WiFi gratuit, une piscine sécuritaire et nage libre avec chaises longues et une douche.", "it" => "Un appartamento per due / tre persone con terrazza privata con vista sul mare. L'appartamento è dotato di aria condizionata e riscaldamento, Wi-Fi gratuito, piscina sicuro e nuoto libero con lettini e doccia.", "de" => "Ein-Zimmer-Wohnung für zwei / drei Personen mit eigener Terrasse mit Blick auf das Meer. Die Wohnung verfügt über eine Klimaanlage und Heizung, kostenfreies WLAN, kostenlosen Safe und einen Swimmingpool mit Liegestühlen und Dusche."),
    "botoReserva" => array("es"=>"Reserva", "en" => "Reservation", "fr" => "Réserve", "it" => "Riserva", "de" => "Reserve"),
    "botoGaleria" => array("es"=>"Galeria", "en" => "Gallery", "fr" => "Galerie", "it" => "Galleria", "de" => "Galerie"),
    "descripccion" => array("es"=>"Descripción", "en" => "Description", "fr" => "Description", "it" => "Descrizione", "de" => "Beschreibung"),
    "video" => array("es"=>"Video", "en" => "Video", "fr" => "Vidéo", "it" => "Video", "de" => "Video"),
    "localicacion" => array("es"=>"Localización", "en" => "Location", "fr" => "Emplacement", "it" => "Posizione", "de" => "Lage"),
    "habitaciones" => array("es"=>"HABITACIONES", "en" => "BEDROOMS", "fr" => "CHAMBRES", "it" => "CAMERE", "de" => "ZIMMER"),
    "cocina" => array("es"=>"cocina", "en" => "BEDROOMS", "fr" => "cuisine", "it" => "cucina", "de" => "Küche"),
    "bano" => array("es"=>"Baño", "en" => "bath", "fr" => "salle de bains", "it" => "bagno", "de" => "Badezimmer"),
    //Informacion BB1
    "habitacionesinfo" => array("es"=>"- Cama de 160cm con colchon de calidad.<br/>- Cuna opcional.<br/> - Sofa cama en sala para una persona.<br/>", "en" => "- 160cm bed with quality mattress. <br/> - Optional cot. <br/> - Sofa bed in living room for one person. <br/>", "fr" => "- 160cm lit avec matelas de qualité <br/> - Lit bébé en option <br/> - Canapé-lit dans le salon pour une <br/> personne.", "it" => "- Letto 160 centimetri con materasso di qualità <br/> - Lettino opzionale <br/> - Divano letto nel soggiorno per una persona <br/>.", "de" => "- 160cm Bett mit hochwertiger Matratze <br/> - Optional Bett <br/> - Schlafsofa im Wohnzimmer für eine Person <br/>"),
    "cocinainfo" => array("es"=>"- Cocina electrica completa con menaje.<br/> - Frigorifico.<br/>- Tostadora.<br/>- Microondas.<br/>- Cafetera.<br/>- Hervidor de Agua.<br/>", "en" => "- 160cm bed with quality mattress. <br/> - Optional cot<br/> - Sofa bed in living room for one person. <br/>", "fr" => "- Cuisine complète électrique avec des ustensiles <br/> - Réfrigérateur <br/> - Grille-pain <br/> - Micro-ondes <br/> -. <br/> Café - Bouilloire <br/>.", "it" => "-. Cucina elettrica completa di utensili <br/> - Frigorifero <br/> - Tostapane <br/> - Microonde <br/> - Caffè <br/> - Bollitore <br/>.", "de" => "- Volle elektrische Küche mit Geschirr <br/> - Kühlschrank <br/> - Toaster <br/> - Mikrowelle <br/> - Kaffee <br/> - Kettle <br/>"),
    "banoinfo" => array("es"=>"- Secador de pelo<br/>- Espejo de Maquillaje<br/>- Bañera<br/>", "en" => "- Hair dryer <br/> - Make-up mirror <br/> - Bathtub <br/>", "fr" => "- Sèche-cheveux <br/> - <br/> Miroir de maquillage - <br/> Bath", "it" => "- Asciugacapelli <br/> - <br/> specchio da trucco - Bagno <br/>", "de" => "- Haartrockner <br/> - Spiegel Makeup <br/>- Bad <br/>"),
);


/*
 * plantilla => array("es"=>"", "en" => "", "fr" => "", "it" => "", "de" => "")
*/
